# 工作流程的名稱
name: Build, Push, and Deploy Docker Image
# 1. 觸發時機 (當推送到 main 分支時)
on:
  push:
    branches:       
      - main

# 2. 權限設定 (請求寫入 packages 的權限)
permissions:
  contents: read      
  packages: write     

# 3. 工作
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 步驟一：下載您的程式碼 (Dockerfile, app.py...)
      - name: Checkout code
        uses: actions/checkout@v4

      # 步驟二：登入 GitHub 容器倉庫 (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 步驟三：建置 Docker 映像並推送
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .         
          push: true         
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

deploy:
    runs-on: ubuntu-latest
    

    needs: build-and-push

    permissions:
      packages: read       

    steps:
      - name: Deploy to EC2 Server

        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}        # 您的 EC2 IP
          username: ${{ secrets.EC2_USER }}    # ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}      # 您的 .pem 金鑰內容
          port: 22                             # SSH 預設 port


          script: |
            # 1. (在 EC2 上) 登入 GHCR
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            # 2. (在 EC2 上) 拉取 (Pull) 最新的 Docker 映像
            docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

            # 3. (在 EC2 上) 停止並移除舊的容器
            docker stop devops-app || true
            docker rm devops-app || true

            # 4. (在 EC2 上) 啟動新容器
            docker run -d -p 8080:8080 --name devops-app --restart always ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest